plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'net.novacubegame'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "net.novacubegame"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        resConfigs "en"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    externalNativeBuild {
        cmake {
            path file('../../CMakeLists.txt')
            version '4.1.2'
        }
    }
    buildFeatures {
        prefab true
    }

    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'x86_64'
            universalApk true
        }
    }

    bundle {
        abi {
            enableSplit true
        }
    }
    ndkVersion '29.0.14206865'
    buildToolsVersion '36.1.0'
}

dependencies {
    implementation files('libs/SDL3-3.5.0.aar')
}

// Map for the version code that gives each ABI a value.
ext.abiCodes = ['arm64-v8a': 1, 'x86_64': 2]

androidComponents {
    onVariants(selector().all()) { variant ->
        variant.outputs.each { output ->
            def abi = output.filters.find { it.filterType.name() == 'ABI' }?.identifier
            def baseAbiCode = project.ext.abiCodes.get(abi)
            if (baseAbiCode != null) {
                def currentVersionCode = output.versionCode.get() ?: 0
                output.versionCode.set(baseAbiCode * 100000 + currentVersionCode)
            }
        }
    }
}
