import binascii, math, sys, time
from compression import zstd

def render_glyph(glyph) -> str | None:
    if not glyph:
        return None

    result: list[str] = []
    bitmap = glyph['bitmap']
    wide = glyph['wide']
    for y in range(16):
        line = bitmap[y * (2 if wide else 1)]
        line_out = ''
        for x in range(8):
            line_out += '██' if line & 1 << (7 - x) != 0 else '  '
        if wide:
            line = bitmap[y * 2 + 1]
            for x in range(8):
                line_out += '██' if line & 1 << (7 - x) != 0 else '  '
        result.append(line_out)
    return result


def render_string(string) -> str:
    rendered_glyphs = []
    for char in string:
        glyph = glyphs[ord(char)]
        if glyph:
            rendered_glyphs.append(render_glyph(glyph))

    result = ''
    for i in range(16):
        for glyph in rendered_glyphs:
            result += glyph[i]
        result += '\n'
    return result


HEX_DIGITS = (
    (0x6,0x9,0x9,0x9,0x6),  # 0
    (0x2,0x6,0x2,0x2,0x7),  # 1
    (0xF,0x1,0xF,0x8,0xF),  # 2
    (0xE,0x1,0x7,0x1,0xE),  # 3
    (0x9,0x9,0xF,0x1,0x1),  # 4
    (0xF,0x8,0xF,0x1,0xF),  # 5
    (0x6,0x8,0xE,0x9,0x6),  # 6
    (0xF,0x1,0x2,0x4,0x4),  # 7
    (0x6,0x9,0x6,0x9,0x6),  # 8
    (0x6,0x9,0x7,0x1,0x6),  # 9
    (0xF,0x9,0xF,0x9,0x9),  # A
    (0xE,0x9,0xE,0x9,0xE),  # B
    (0x7,0x8,0x8,0x8,0x7),  # C
    (0xE,0x9,0x9,0x9,0xE),  # D
    (0xF,0x8,0xE,0x8,0xF),  # E
    (0xF,0x8,0xE,0x8,0x8),  # F
)


def unihexgen_bitmap(codepoint: int) -> bytes:
    """Reproduce the 16x16 placeholder generated by Unifont's unihexgen."""
    digit_count = 4 if codepoint <= 0xFFFF else 6
    digits = [(codepoint >> shift) & 0xF for shift in range((digit_count - 1) * 4, -1, -4)]

    if digit_count == 4:
        rows = [0x0000] + [0x7FFE] * 14 + [0x0000]
        groups = (digits[:2], digits[2:])
        shifts = (9, 3)
    else:
        rows = [0x0000] + [0xFFFF] * 14 + [0x0000]
        groups = (digits[:3], digits[3:])
        shifts = (11, 6, 1)

    for first_row, group in zip((2, 9), groups):
        for digit_row in range(5):
            digit_bits = 0
            for digit, shift in zip(group, shifts):
                digit_bits |= HEX_DIGITS[digit][digit_row] << shift
            rows[first_row + digit_row] ^= digit_bits

    return b''.join(row.to_bytes(2, 'big') for row in rows)


def is_missing_glyph(glyph) -> bool:
    return glyph['wide'] and glyph['bitmap'] == unihexgen_bitmap(glyph['codepoint'])


with open(sys.argv[1]) as lines:
    lines = lines.read()

lines = lines.split('\n')

glyphs: dict[int, dict[str, int | bool | bytes]] = {}

skipped = 0
total_bitmap_bytes = 0
for l in lines:
    if len(l) == 0:
        # skip the last line that is empty
        continue

    codepoint, hex = l.split(':')
    codepoint = int(codepoint, 16)
    length = len(hex)
    if length == 32:
        wide = False
        total_bitmap_bytes += 16
    elif length == 64:
        wide = True
        total_bitmap_bytes += 32
    else:
        raise BaseException(f'Codepoint {codepoint} has an unexpected length {length}')
    new_glyph = {
        'codepoint': codepoint,
        'wide': wide,
        'bitmap': binascii.unhexlify(hex),
    }

    skip = is_missing_glyph(new_glyph)

    if skip:
        skipped += 1
        continue

    glyphs[codepoint] = new_glyph

included = len(glyphs)
print(f'Processed {included + skipped} glyphs. {included} included, {skipped} skipped. {total_bitmap_bytes} font bitmap bytes, {total_bitmap_bytes * 8} bits.')

# Derive ranges from the glyphs that survived filtering.
all_ranges: list[tuple[int, int]] = []
codepoints = sorted(glyphs)

range_start = previous_codepoint = codepoints[0]
for codepoint in codepoints[1:]:
    if codepoint != previous_codepoint + 1:
        all_ranges.append((range_start, previous_codepoint))
        range_start = codepoint
    previous_codepoint = codepoint
all_ranges.append((range_start, previous_codepoint))

ranges = [range_ for range_ in all_ranges if range_[0] != range_[1]]
single_codepoint_ranges = [range_[0] for range_ in all_ranges if range_[0] == range_[1]]

with open('ranges.txt', 'wt') as f:
    for codepoint in ranges:
        f.write(f'0x{codepoint[0]:X} - 0x{codepoint[1]:X}\n')

with open('single_codepoint_ranges.txt', 'wt') as f:
    for codepoint in single_codepoint_ranges:
        f.write(f'0x{codepoint:X}\n')

data = bytearray()

data.extend(included.to_bytes(4, byteorder='little'))

# bit array where 0 = 8x16 bitmap, 1 = 16x16 bitmap
sizes = bytearray(math.ceil(included / 8))
print(f'The bit array has a size of {len(sizes)} bytes.')
for i, glyph in enumerate(glyphs.values()):
    wide = glyph['wide']
    if wide:
        sizes[math.floor(i / 8)] |= 1 << i % 8
data.extend(sizes)

# align to 4 bytes
written = len(sizes)
padding = math.ceil(written / 4) * 4 - written
data.extend(b'\0' * padding)
print(f'There were {padding} bytes of padding.')

range_count = len(all_ranges)
print(f'There are {range_count} ranges.')
data.extend(range_count.to_bytes(4, byteorder='little'))
for range_ in all_ranges:
    begin = range_[0]
    data.extend(begin.to_bytes(4, byteorder='little'))
    end = range_[1]
    data.extend(end.to_bytes(4, byteorder='little'))

for glyph in glyphs.values():
    bitmap = glyph['bitmap']
    data.extend(bitmap)

with open('font.ncfn', 'wb') as f:
    signature = 'NCFN'
    f.write(signature.encode('ascii'))

    version = 1
    f.write(version.to_bytes(4, byteorder='little'))

    f.write(zstd.compress(data, level=22))

if len(sys.argv) >= 3:
    string_to_render = sys.argv[2]
    print(f'Rendering "{string_to_render}"')
    if string_to_render:
        print(render_string(string_to_render))
