#pragma once
#ifndef NOVACUBE_NUKLEAR_CONFIG_H_
#define NOVACUBE_NUKLEAR_CONFIG_H_

#include <novacube/macros.h>
#include <novacube/standard_functions.h>

#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_STANDARD_BOOL
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_UINT_DRAW_INDEX
#define NK_BUTTON_TRIGGER_ON_RELEASE
#define NK_KEYSTATE_BASED_INPUT
#define NK_ASSERT NC_ASSERT

NC_IGNORE_ALL_WARNINGS_BEGIN
#include <nuklear.h>
NC_IGNORE_ALL_WARNINGS_END

#endif
